In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf


In [4]:
df = pd.read_csv(r"C:\Users\DELL\OneDrive\Documents\churn model.csv")
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
x = df.iloc[:,3:-1].values
y = df.iloc[:,-1].values

In [6]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [7]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,2] = le.fit_transform(x[:,2])

In [11]:
x[:,2]

array([0, 0, 0, ..., 0, 1, 0], dtype=object)

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer([("encoder", OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [15]:
x

array([[ 1.        ,  0.        ,  0.99720391, ...,  0.64609167,
         0.97024255,  0.02188649],
       [ 1.        ,  0.        , -1.00280393, ..., -1.54776799,
         0.97024255,  0.21653375],
       [ 1.        ,  0.        ,  0.99720391, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [ 1.        ,  0.        ,  0.99720391, ..., -1.54776799,
         0.97024255, -1.00864308],
       [ 0.        ,  1.        , -1.00280393, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [ 1.        ,  0.        ,  0.99720391, ...,  0.64609167,
        -1.03067011, -1.07636976]])

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)

In [17]:
x

array([[ 0.57873591, -0.57873591,  0.99720391, ...,  0.64609167,
         0.97024255,  0.02188649],
       [ 0.57873591, -0.57873591, -1.00280393, ..., -1.54776799,
         0.97024255,  0.21653375],
       [ 0.57873591, -0.57873591,  0.99720391, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [ 0.57873591, -0.57873591,  0.99720391, ..., -1.54776799,
         0.97024255, -1.00864308],
       [-1.72790383,  1.72790383, -1.00280393, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [ 0.57873591, -0.57873591,  0.99720391, ...,  0.64609167,
        -1.03067011, -1.07636976]])

In [18]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=0)

In [22]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
#ann.add(tf.keras.layers.Dense(units=5, activation='relu'))
#nn.add(tf.keras.layers.Dense(units=4, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
ann.fit(x_train, y_train, batch_size=32, epochs=100,validation_data=(x_test, y_test))

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7830 - loss: 0.5446 - val_accuracy: 0.8125 - val_loss: 0.4776
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8086 - loss: 0.4631 - val_accuracy: 0.8115 - val_loss: 0.4372
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8119 - loss: 0.4368 - val_accuracy: 0.8155 - val_loss: 0.4195
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8152 - loss: 0.4230 - val_accuracy: 0.8215 - val_loss: 0.4063
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8210 - loss: 0.4106 - val_accuracy: 0.8350 - val_loss: 0.3926
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8285 - loss: 0.3972 - val_accuracy: 0.8410 - val_loss: 0.3777
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8381 - loss: 0.3840 - val_accuracy: 0.8525 - val_loss: 0.3680
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8450 - loss: 0.3741 - val_accu

In [23]:
y_pred = ann.predict(x_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step


In [31]:
y_pred = (y_pred > 0.5)

In [32]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [34]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [35]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1511   84]
 [ 199  206]]


In [37]:
ac = accuracy_score(y_test, y_pred)
print(ac)

0.8585
